language: node_js
node_js: "6"

cache:
  yarn: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: build
  repo: ResistanceCN/resistancecn.github.io
  target_branch: master
  name: ADA
  email: ada@blue.io
  on:
    branch: master
# E: Build LifeCycle

branches:
  only:
    - master
