language: node_js
node_js: "6"

cache:
  yarn: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build

after_script:
  - cd build
  - git init
  - git config user.name "ADA"
  - git config user.email "ada@blue.io"
  - git add .
  - git commit -m "Update preview"
  - git push --force --quiet "https://${GH_AUTH}@github.com/ResistanceCN/resistancecn.github.io.git" master
# E: Build LifeCycle

branches:
  only:
    - master
