export const AUTH_RESET = 'AUTH_RESET';
export const GOOGLE_SIGNED_IN = 'GOOGLE_SIGNED_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ENABLE_IMMERSIVE = 'ENTER_IMMERSIVE';
export const DISABLE_IMMERSIVE = 'ENTER_IMMERSIVE';
